// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUvF-1w9qSBEiIaXJSy5qxPTS246bbCMk',
    appId: '1:570220862213:web:8f37b14f96cefbbcbbb56c',
    messagingSenderId: '570220862213',
    projectId: 'cosense-9d538',
    authDomain: 'cosense-9d538.firebaseapp.com',
    databaseURL: 'https://cosense-9d538-default-rtdb.firebaseio.com',
    storageBucket: 'cosense-9d538.appspot.com',
    measurementId: 'G-P5BPFF5C18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBFzXJDoVgYf_k4rdEM_Jflb4QNoKNRoI',
    appId: '1:570220862213:android:705277101a5e8918bbb56c',
    messagingSenderId: '570220862213',
    projectId: 'cosense-9d538',
    databaseURL: 'https://cosense-9d538-default-rtdb.firebaseio.com',
    storageBucket: 'cosense-9d538.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcUWHdlFtx9ZuvMCUtpCfS4VnGYoTe9rU',
    appId: '1:570220862213:ios:1123d02520c571a3bbb56c',
    messagingSenderId: '570220862213',
    projectId: 'cosense-9d538',
    databaseURL: 'https://cosense-9d538-default-rtdb.firebaseio.com',
    storageBucket: 'cosense-9d538.appspot.com',
    iosClientId: '570220862213-hsh7n0iqnvkhcp7dqr4gm4tk83ha6rof.apps.googleusercontent.com',
    iosBundleId: 'com.example.coSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcUWHdlFtx9ZuvMCUtpCfS4VnGYoTe9rU',
    appId: '1:570220862213:ios:1123d02520c571a3bbb56c',
    messagingSenderId: '570220862213',
    projectId: 'cosense-9d538',
    databaseURL: 'https://cosense-9d538-default-rtdb.firebaseio.com',
    storageBucket: 'cosense-9d538.appspot.com',
    iosClientId: '570220862213-hsh7n0iqnvkhcp7dqr4gm4tk83ha6rof.apps.googleusercontent.com',
    iosBundleId: 'com.example.coSense',
  );
}
