/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_logo = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maps = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_button = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speed = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cosense_logo = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData distance = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gyroscope = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
